//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication1.AccessServ {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://yixiubox.com:5000/", ConfigurationName="AccessServ.AccessServiceSoap")]
    public interface AccessServiceSoap {
        
        // CODEGEN: 命名空间 http://yixiubox.com:5000/ 的元素名称 HelloWorldResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://yixiubox.com:5000/HelloWorld", ReplyAction="*")]
        WpfApplication1.AccessServ.HelloWorldResponse HelloWorld(WpfApplication1.AccessServ.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://yixiubox.com:5000/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<WpfApplication1.AccessServ.HelloWorldResponse> HelloWorldAsync(WpfApplication1.AccessServ.HelloWorldRequest request);
        
        // CODEGEN: 命名空间 http://yixiubox.com:5000/ 的元素名称 strjson 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://yixiubox.com:5000/Login", ReplyAction="*")]
        WpfApplication1.AccessServ.LoginResponse Login(WpfApplication1.AccessServ.LoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://yixiubox.com:5000/Login", ReplyAction="*")]
        System.Threading.Tasks.Task<WpfApplication1.AccessServ.LoginResponse> LoginAsync(WpfApplication1.AccessServ.LoginRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://yixiubox.com:5000/", Order=0)]
        public WpfApplication1.AccessServ.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(WpfApplication1.AccessServ.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://yixiubox.com:5000/", Order=0)]
        public WpfApplication1.AccessServ.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(WpfApplication1.AccessServ.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://yixiubox.com:5000/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Login", Namespace="http://yixiubox.com:5000/", Order=0)]
        public WpfApplication1.AccessServ.LoginRequestBody Body;
        
        public LoginRequest() {
        }
        
        public LoginRequest(WpfApplication1.AccessServ.LoginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://yixiubox.com:5000/")]
    public partial class LoginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strjson;
        
        public LoginRequestBody() {
        }
        
        public LoginRequestBody(string strjson) {
            this.strjson = strjson;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginResponse", Namespace="http://yixiubox.com:5000/", Order=0)]
        public WpfApplication1.AccessServ.LoginResponseBody Body;
        
        public LoginResponse() {
        }
        
        public LoginResponse(WpfApplication1.AccessServ.LoginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://yixiubox.com:5000/")]
    public partial class LoginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string LoginResult;
        
        public LoginResponseBody() {
        }
        
        public LoginResponseBody(string LoginResult) {
            this.LoginResult = LoginResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AccessServiceSoapChannel : WpfApplication1.AccessServ.AccessServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AccessServiceSoapClient : System.ServiceModel.ClientBase<WpfApplication1.AccessServ.AccessServiceSoap>, WpfApplication1.AccessServ.AccessServiceSoap {
        
        public AccessServiceSoapClient() {
        }
        
        public AccessServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AccessServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccessServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccessServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WpfApplication1.AccessServ.HelloWorldResponse WpfApplication1.AccessServ.AccessServiceSoap.HelloWorld(WpfApplication1.AccessServ.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            WpfApplication1.AccessServ.HelloWorldRequest inValue = new WpfApplication1.AccessServ.HelloWorldRequest();
            inValue.Body = new WpfApplication1.AccessServ.HelloWorldRequestBody();
            WpfApplication1.AccessServ.HelloWorldResponse retVal = ((WpfApplication1.AccessServ.AccessServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WpfApplication1.AccessServ.HelloWorldResponse> WpfApplication1.AccessServ.AccessServiceSoap.HelloWorldAsync(WpfApplication1.AccessServ.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<WpfApplication1.AccessServ.HelloWorldResponse> HelloWorldAsync() {
            WpfApplication1.AccessServ.HelloWorldRequest inValue = new WpfApplication1.AccessServ.HelloWorldRequest();
            inValue.Body = new WpfApplication1.AccessServ.HelloWorldRequestBody();
            return ((WpfApplication1.AccessServ.AccessServiceSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WpfApplication1.AccessServ.LoginResponse WpfApplication1.AccessServ.AccessServiceSoap.Login(WpfApplication1.AccessServ.LoginRequest request) {
            return base.Channel.Login(request);
        }
        
        public string Login(string strjson) {
            WpfApplication1.AccessServ.LoginRequest inValue = new WpfApplication1.AccessServ.LoginRequest();
            inValue.Body = new WpfApplication1.AccessServ.LoginRequestBody();
            inValue.Body.strjson = strjson;
            WpfApplication1.AccessServ.LoginResponse retVal = ((WpfApplication1.AccessServ.AccessServiceSoap)(this)).Login(inValue);
            return retVal.Body.LoginResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WpfApplication1.AccessServ.LoginResponse> WpfApplication1.AccessServ.AccessServiceSoap.LoginAsync(WpfApplication1.AccessServ.LoginRequest request) {
            return base.Channel.LoginAsync(request);
        }
        
        public System.Threading.Tasks.Task<WpfApplication1.AccessServ.LoginResponse> LoginAsync(string strjson) {
            WpfApplication1.AccessServ.LoginRequest inValue = new WpfApplication1.AccessServ.LoginRequest();
            inValue.Body = new WpfApplication1.AccessServ.LoginRequestBody();
            inValue.Body.strjson = strjson;
            return ((WpfApplication1.AccessServ.AccessServiceSoap)(this)).LoginAsync(inValue);
        }
    }
}
