//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication1.EquipmentServ {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://yixiubox.com:5000/", ConfigurationName="EquipmentServ.EquipmentServiceSoap")]
    public interface EquipmentServiceSoap {
        
        // CODEGEN: 命名空间 http://yixiubox.com:5000/ 的元素名称 strjson 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://yixiubox.com:5000/GetEquipmentInfo", ReplyAction="*")]
        WpfApplication1.EquipmentServ.GetEquipmentInfoResponse GetEquipmentInfo(WpfApplication1.EquipmentServ.GetEquipmentInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://yixiubox.com:5000/GetEquipmentInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<WpfApplication1.EquipmentServ.GetEquipmentInfoResponse> GetEquipmentInfoAsync(WpfApplication1.EquipmentServ.GetEquipmentInfoRequest request);
        
        // CODEGEN: 命名空间 http://yixiubox.com:5000/ 的元素名称 strjson 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://yixiubox.com:5000/Active", ReplyAction="*")]
        WpfApplication1.EquipmentServ.ActiveResponse Active(WpfApplication1.EquipmentServ.ActiveRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://yixiubox.com:5000/Active", ReplyAction="*")]
        System.Threading.Tasks.Task<WpfApplication1.EquipmentServ.ActiveResponse> ActiveAsync(WpfApplication1.EquipmentServ.ActiveRequest request);
        
        // CODEGEN: 命名空间 http://yixiubox.com:5000/ 的元素名称 strjson 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://yixiubox.com:5000/UpdateIPList", ReplyAction="*")]
        WpfApplication1.EquipmentServ.UpdateIPListResponse UpdateIPList(WpfApplication1.EquipmentServ.UpdateIPListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://yixiubox.com:5000/UpdateIPList", ReplyAction="*")]
        System.Threading.Tasks.Task<WpfApplication1.EquipmentServ.UpdateIPListResponse> UpdateIPListAsync(WpfApplication1.EquipmentServ.UpdateIPListRequest request);
        
        // CODEGEN: 命名空间 http://yixiubox.com:5000/ 的元素名称 HelloWorldResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://yixiubox.com:5000/HelloWorld", ReplyAction="*")]
        WpfApplication1.EquipmentServ.HelloWorldResponse HelloWorld(WpfApplication1.EquipmentServ.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://yixiubox.com:5000/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<WpfApplication1.EquipmentServ.HelloWorldResponse> HelloWorldAsync(WpfApplication1.EquipmentServ.HelloWorldRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetEquipmentInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetEquipmentInfo", Namespace="http://yixiubox.com:5000/", Order=0)]
        public WpfApplication1.EquipmentServ.GetEquipmentInfoRequestBody Body;
        
        public GetEquipmentInfoRequest() {
        }
        
        public GetEquipmentInfoRequest(WpfApplication1.EquipmentServ.GetEquipmentInfoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://yixiubox.com:5000/")]
    public partial class GetEquipmentInfoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strjson;
        
        public GetEquipmentInfoRequestBody() {
        }
        
        public GetEquipmentInfoRequestBody(string strjson) {
            this.strjson = strjson;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetEquipmentInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetEquipmentInfoResponse", Namespace="http://yixiubox.com:5000/", Order=0)]
        public WpfApplication1.EquipmentServ.GetEquipmentInfoResponseBody Body;
        
        public GetEquipmentInfoResponse() {
        }
        
        public GetEquipmentInfoResponse(WpfApplication1.EquipmentServ.GetEquipmentInfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://yixiubox.com:5000/")]
    public partial class GetEquipmentInfoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetEquipmentInfoResult;
        
        public GetEquipmentInfoResponseBody() {
        }
        
        public GetEquipmentInfoResponseBody(string GetEquipmentInfoResult) {
            this.GetEquipmentInfoResult = GetEquipmentInfoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ActiveRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Active", Namespace="http://yixiubox.com:5000/", Order=0)]
        public WpfApplication1.EquipmentServ.ActiveRequestBody Body;
        
        public ActiveRequest() {
        }
        
        public ActiveRequest(WpfApplication1.EquipmentServ.ActiveRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://yixiubox.com:5000/")]
    public partial class ActiveRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strjson;
        
        public ActiveRequestBody() {
        }
        
        public ActiveRequestBody(string strjson) {
            this.strjson = strjson;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ActiveResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ActiveResponse", Namespace="http://yixiubox.com:5000/", Order=0)]
        public WpfApplication1.EquipmentServ.ActiveResponseBody Body;
        
        public ActiveResponse() {
        }
        
        public ActiveResponse(WpfApplication1.EquipmentServ.ActiveResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://yixiubox.com:5000/")]
    public partial class ActiveResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ActiveResult;
        
        public ActiveResponseBody() {
        }
        
        public ActiveResponseBody(string ActiveResult) {
            this.ActiveResult = ActiveResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateIPListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateIPList", Namespace="http://yixiubox.com:5000/", Order=0)]
        public WpfApplication1.EquipmentServ.UpdateIPListRequestBody Body;
        
        public UpdateIPListRequest() {
        }
        
        public UpdateIPListRequest(WpfApplication1.EquipmentServ.UpdateIPListRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://yixiubox.com:5000/")]
    public partial class UpdateIPListRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strjson;
        
        public UpdateIPListRequestBody() {
        }
        
        public UpdateIPListRequestBody(string strjson) {
            this.strjson = strjson;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateIPListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateIPListResponse", Namespace="http://yixiubox.com:5000/", Order=0)]
        public WpfApplication1.EquipmentServ.UpdateIPListResponseBody Body;
        
        public UpdateIPListResponse() {
        }
        
        public UpdateIPListResponse(WpfApplication1.EquipmentServ.UpdateIPListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://yixiubox.com:5000/")]
    public partial class UpdateIPListResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UpdateIPListResult;
        
        public UpdateIPListResponseBody() {
        }
        
        public UpdateIPListResponseBody(string UpdateIPListResult) {
            this.UpdateIPListResult = UpdateIPListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://yixiubox.com:5000/", Order=0)]
        public WpfApplication1.EquipmentServ.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(WpfApplication1.EquipmentServ.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://yixiubox.com:5000/", Order=0)]
        public WpfApplication1.EquipmentServ.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(WpfApplication1.EquipmentServ.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://yixiubox.com:5000/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface EquipmentServiceSoapChannel : WpfApplication1.EquipmentServ.EquipmentServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EquipmentServiceSoapClient : System.ServiceModel.ClientBase<WpfApplication1.EquipmentServ.EquipmentServiceSoap>, WpfApplication1.EquipmentServ.EquipmentServiceSoap {
        
        public EquipmentServiceSoapClient() {
        }
        
        public EquipmentServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EquipmentServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EquipmentServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EquipmentServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WpfApplication1.EquipmentServ.GetEquipmentInfoResponse WpfApplication1.EquipmentServ.EquipmentServiceSoap.GetEquipmentInfo(WpfApplication1.EquipmentServ.GetEquipmentInfoRequest request) {
            return base.Channel.GetEquipmentInfo(request);
        }
        
        public string GetEquipmentInfo(string strjson) {
            WpfApplication1.EquipmentServ.GetEquipmentInfoRequest inValue = new WpfApplication1.EquipmentServ.GetEquipmentInfoRequest();
            inValue.Body = new WpfApplication1.EquipmentServ.GetEquipmentInfoRequestBody();
            inValue.Body.strjson = strjson;
            WpfApplication1.EquipmentServ.GetEquipmentInfoResponse retVal = ((WpfApplication1.EquipmentServ.EquipmentServiceSoap)(this)).GetEquipmentInfo(inValue);
            return retVal.Body.GetEquipmentInfoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WpfApplication1.EquipmentServ.GetEquipmentInfoResponse> WpfApplication1.EquipmentServ.EquipmentServiceSoap.GetEquipmentInfoAsync(WpfApplication1.EquipmentServ.GetEquipmentInfoRequest request) {
            return base.Channel.GetEquipmentInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<WpfApplication1.EquipmentServ.GetEquipmentInfoResponse> GetEquipmentInfoAsync(string strjson) {
            WpfApplication1.EquipmentServ.GetEquipmentInfoRequest inValue = new WpfApplication1.EquipmentServ.GetEquipmentInfoRequest();
            inValue.Body = new WpfApplication1.EquipmentServ.GetEquipmentInfoRequestBody();
            inValue.Body.strjson = strjson;
            return ((WpfApplication1.EquipmentServ.EquipmentServiceSoap)(this)).GetEquipmentInfoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WpfApplication1.EquipmentServ.ActiveResponse WpfApplication1.EquipmentServ.EquipmentServiceSoap.Active(WpfApplication1.EquipmentServ.ActiveRequest request) {
            return base.Channel.Active(request);
        }
        
        public string Active(string strjson) {
            WpfApplication1.EquipmentServ.ActiveRequest inValue = new WpfApplication1.EquipmentServ.ActiveRequest();
            inValue.Body = new WpfApplication1.EquipmentServ.ActiveRequestBody();
            inValue.Body.strjson = strjson;
            WpfApplication1.EquipmentServ.ActiveResponse retVal = ((WpfApplication1.EquipmentServ.EquipmentServiceSoap)(this)).Active(inValue);
            return retVal.Body.ActiveResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WpfApplication1.EquipmentServ.ActiveResponse> WpfApplication1.EquipmentServ.EquipmentServiceSoap.ActiveAsync(WpfApplication1.EquipmentServ.ActiveRequest request) {
            return base.Channel.ActiveAsync(request);
        }
        
        public System.Threading.Tasks.Task<WpfApplication1.EquipmentServ.ActiveResponse> ActiveAsync(string strjson) {
            WpfApplication1.EquipmentServ.ActiveRequest inValue = new WpfApplication1.EquipmentServ.ActiveRequest();
            inValue.Body = new WpfApplication1.EquipmentServ.ActiveRequestBody();
            inValue.Body.strjson = strjson;
            return ((WpfApplication1.EquipmentServ.EquipmentServiceSoap)(this)).ActiveAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WpfApplication1.EquipmentServ.UpdateIPListResponse WpfApplication1.EquipmentServ.EquipmentServiceSoap.UpdateIPList(WpfApplication1.EquipmentServ.UpdateIPListRequest request) {
            return base.Channel.UpdateIPList(request);
        }
        
        public string UpdateIPList(string strjson) {
            WpfApplication1.EquipmentServ.UpdateIPListRequest inValue = new WpfApplication1.EquipmentServ.UpdateIPListRequest();
            inValue.Body = new WpfApplication1.EquipmentServ.UpdateIPListRequestBody();
            inValue.Body.strjson = strjson;
            WpfApplication1.EquipmentServ.UpdateIPListResponse retVal = ((WpfApplication1.EquipmentServ.EquipmentServiceSoap)(this)).UpdateIPList(inValue);
            return retVal.Body.UpdateIPListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WpfApplication1.EquipmentServ.UpdateIPListResponse> WpfApplication1.EquipmentServ.EquipmentServiceSoap.UpdateIPListAsync(WpfApplication1.EquipmentServ.UpdateIPListRequest request) {
            return base.Channel.UpdateIPListAsync(request);
        }
        
        public System.Threading.Tasks.Task<WpfApplication1.EquipmentServ.UpdateIPListResponse> UpdateIPListAsync(string strjson) {
            WpfApplication1.EquipmentServ.UpdateIPListRequest inValue = new WpfApplication1.EquipmentServ.UpdateIPListRequest();
            inValue.Body = new WpfApplication1.EquipmentServ.UpdateIPListRequestBody();
            inValue.Body.strjson = strjson;
            return ((WpfApplication1.EquipmentServ.EquipmentServiceSoap)(this)).UpdateIPListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WpfApplication1.EquipmentServ.HelloWorldResponse WpfApplication1.EquipmentServ.EquipmentServiceSoap.HelloWorld(WpfApplication1.EquipmentServ.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            WpfApplication1.EquipmentServ.HelloWorldRequest inValue = new WpfApplication1.EquipmentServ.HelloWorldRequest();
            inValue.Body = new WpfApplication1.EquipmentServ.HelloWorldRequestBody();
            WpfApplication1.EquipmentServ.HelloWorldResponse retVal = ((WpfApplication1.EquipmentServ.EquipmentServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WpfApplication1.EquipmentServ.HelloWorldResponse> WpfApplication1.EquipmentServ.EquipmentServiceSoap.HelloWorldAsync(WpfApplication1.EquipmentServ.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<WpfApplication1.EquipmentServ.HelloWorldResponse> HelloWorldAsync() {
            WpfApplication1.EquipmentServ.HelloWorldRequest inValue = new WpfApplication1.EquipmentServ.HelloWorldRequest();
            inValue.Body = new WpfApplication1.EquipmentServ.HelloWorldRequestBody();
            return ((WpfApplication1.EquipmentServ.EquipmentServiceSoap)(this)).HelloWorldAsync(inValue);
        }
    }
}
