//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication1.TimingServ {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://yixiubox.com:5000/", ConfigurationName="TimingServ.TimingServiceSoap")]
    public interface TimingServiceSoap {
        
        // CODEGEN: 命名空间 http://yixiubox.com:5000/ 的元素名称 strjson 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://yixiubox.com:5000/GetTimingList", ReplyAction="*")]
        WpfApplication1.TimingServ.GetTimingListResponse GetTimingList(WpfApplication1.TimingServ.GetTimingListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://yixiubox.com:5000/GetTimingList", ReplyAction="*")]
        System.Threading.Tasks.Task<WpfApplication1.TimingServ.GetTimingListResponse> GetTimingListAsync(WpfApplication1.TimingServ.GetTimingListRequest request);
        
        // CODEGEN: 命名空间 http://yixiubox.com:5000/ 的元素名称 HelloWorldResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://yixiubox.com:5000/HelloWorld", ReplyAction="*")]
        WpfApplication1.TimingServ.HelloWorldResponse HelloWorld(WpfApplication1.TimingServ.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://yixiubox.com:5000/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<WpfApplication1.TimingServ.HelloWorldResponse> HelloWorldAsync(WpfApplication1.TimingServ.HelloWorldRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTimingListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTimingList", Namespace="http://yixiubox.com:5000/", Order=0)]
        public WpfApplication1.TimingServ.GetTimingListRequestBody Body;
        
        public GetTimingListRequest() {
        }
        
        public GetTimingListRequest(WpfApplication1.TimingServ.GetTimingListRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://yixiubox.com:5000/")]
    public partial class GetTimingListRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strjson;
        
        public GetTimingListRequestBody() {
        }
        
        public GetTimingListRequestBody(string strjson) {
            this.strjson = strjson;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTimingListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTimingListResponse", Namespace="http://yixiubox.com:5000/", Order=0)]
        public WpfApplication1.TimingServ.GetTimingListResponseBody Body;
        
        public GetTimingListResponse() {
        }
        
        public GetTimingListResponse(WpfApplication1.TimingServ.GetTimingListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://yixiubox.com:5000/")]
    public partial class GetTimingListResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetTimingListResult;
        
        public GetTimingListResponseBody() {
        }
        
        public GetTimingListResponseBody(string GetTimingListResult) {
            this.GetTimingListResult = GetTimingListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://yixiubox.com:5000/", Order=0)]
        public WpfApplication1.TimingServ.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(WpfApplication1.TimingServ.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://yixiubox.com:5000/", Order=0)]
        public WpfApplication1.TimingServ.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(WpfApplication1.TimingServ.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://yixiubox.com:5000/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TimingServiceSoapChannel : WpfApplication1.TimingServ.TimingServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TimingServiceSoapClient : System.ServiceModel.ClientBase<WpfApplication1.TimingServ.TimingServiceSoap>, WpfApplication1.TimingServ.TimingServiceSoap {
        
        public TimingServiceSoapClient() {
        }
        
        public TimingServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TimingServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TimingServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TimingServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WpfApplication1.TimingServ.GetTimingListResponse WpfApplication1.TimingServ.TimingServiceSoap.GetTimingList(WpfApplication1.TimingServ.GetTimingListRequest request) {
            return base.Channel.GetTimingList(request);
        }
        
        public string GetTimingList(string strjson) {
            WpfApplication1.TimingServ.GetTimingListRequest inValue = new WpfApplication1.TimingServ.GetTimingListRequest();
            inValue.Body = new WpfApplication1.TimingServ.GetTimingListRequestBody();
            inValue.Body.strjson = strjson;
            WpfApplication1.TimingServ.GetTimingListResponse retVal = ((WpfApplication1.TimingServ.TimingServiceSoap)(this)).GetTimingList(inValue);
            return retVal.Body.GetTimingListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WpfApplication1.TimingServ.GetTimingListResponse> WpfApplication1.TimingServ.TimingServiceSoap.GetTimingListAsync(WpfApplication1.TimingServ.GetTimingListRequest request) {
            return base.Channel.GetTimingListAsync(request);
        }
        
        public System.Threading.Tasks.Task<WpfApplication1.TimingServ.GetTimingListResponse> GetTimingListAsync(string strjson) {
            WpfApplication1.TimingServ.GetTimingListRequest inValue = new WpfApplication1.TimingServ.GetTimingListRequest();
            inValue.Body = new WpfApplication1.TimingServ.GetTimingListRequestBody();
            inValue.Body.strjson = strjson;
            return ((WpfApplication1.TimingServ.TimingServiceSoap)(this)).GetTimingListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WpfApplication1.TimingServ.HelloWorldResponse WpfApplication1.TimingServ.TimingServiceSoap.HelloWorld(WpfApplication1.TimingServ.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            WpfApplication1.TimingServ.HelloWorldRequest inValue = new WpfApplication1.TimingServ.HelloWorldRequest();
            inValue.Body = new WpfApplication1.TimingServ.HelloWorldRequestBody();
            WpfApplication1.TimingServ.HelloWorldResponse retVal = ((WpfApplication1.TimingServ.TimingServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WpfApplication1.TimingServ.HelloWorldResponse> WpfApplication1.TimingServ.TimingServiceSoap.HelloWorldAsync(WpfApplication1.TimingServ.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<WpfApplication1.TimingServ.HelloWorldResponse> HelloWorldAsync() {
            WpfApplication1.TimingServ.HelloWorldRequest inValue = new WpfApplication1.TimingServ.HelloWorldRequest();
            inValue.Body = new WpfApplication1.TimingServ.HelloWorldRequestBody();
            return ((WpfApplication1.TimingServ.TimingServiceSoap)(this)).HelloWorldAsync(inValue);
        }
    }
}
